default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: import_csv_development

test:
  <<: *default
  database: import_csv_test

production:
  <<: *default
  database: import_csv_production
  username: rails_kata
  password: <%= ENV['RAILS_KATA_DATABASE_PASSWORD'] %>
